---
title: "README"
date: "2026-06-10"
authors:
- "Friso Harff (7526946)"
- "Marije Jansen (1277596)"
- "Franciszek Koziołkiewicz (2383012)"
- "Leander van der Waal (7180063)"
format:
  html:
    toc: true
    toc-depth: 3
---

# Overview

## Purpose

This app can be used for comparing the performance data of two Pokemon, seeing how two base metrics correlate with each other, and learning about how well one attribute can be used to predict another attribute depending on the size of the train split. The app can be used by anyone interested in Pokemon and the correlation of core mechanics, or anyone who wants to learn about the effects of different train splits with a fun example.

## Main Features

-   Feature 1: Comparing the metrics of two chosen Pokemon.
-   Feature 2: Finding the correlation between two attributes.
-   Feature 3: Learning about the effect of different train splits.

------------------------------------------------------------------------

# Application Design

## Design Goals

When designing this app, the key principles that guided development are accessibility, clear visual communication and simplicity over feature richness. The app is designed to be usable by anyone, regardless of their shiny knowledge or Pokemon knowledge, as it is easy to figure out how inputs affect the plots. The visual communication is guided by short texts explaining what each input is and by going for simplicity over feature richness, the plots are easy to interpret.

## User Workflow

To use the app, one start by just loading the app. Certain default values are selected to make the app work instantly without user input. If desired, the user can change the inputs from the default values, and the plots are updated automatically according to the new inputs.

## Interface Choices

### Layout

The app uses a layout where a sidebar on the left is used for inputs, and the main panel shows the output plots. The sidebar is clearly sectioned into three parts, one for each displayed chart. The first plot the user can choose to see either the radar or the bar plot, as this allows for a less cluttered look. The plots are accompanied by a reactive text to assist the user interpreting the plot.

### Visualizations

#### First graph: Radar or Bar Chart

**Purpose**

The first graph provides insight in how different Pokemon compare in stats.

**Why this chart type?**

A radar chart was chosen to recreate the original Pokemon feel, as this can also be found in multiple Pokemon games. As radar charts are not good visualizations for interpreting absolute values, a bar chart option was added to still allow for proper comparison if desired. The bar chart also allows for more insight in how certain stats are on a different scale than others, as a radar chart uses normalized values. The bar chart is made horizontal to allow for a cleaner look with the stat labels next to the bars.

**Alternatives considered**

An alternative considered is two bar charts where the left one is flipped horizontally, so the y-axes could be merged. This was not done as it would make adding labels to the different stats inconvenient for both development and readability.

#### Second graph: Scatterplot with linear regression

**Purpose**

The scatterplot shows how two stats are distributed over Pokemon, and the linear regression makes it easy to see how two stats are correlated.

**Why this chart type?**

The scatterplot clearly shows the distribution of different Pokemon across two dimensions, while also being an appropriate chart type to include a linear regression model. A scatterplot is the most suitable visualization presenting linear relationship between two continuous variables. It allows to clearly observe the direction and strength of the relationship. Moreover, by using scatterplot it is feasible to show latent features of relationship e.g. clustering and outliers. Finally scatterplot seems the most suitable chart type to adopt interactive tools. Through the implementation of different colors representing interaction term features of each category can be clearly shown.

**Alternatives considered**

A hexbin plot has been considered as an alternative, but this was not fit for the filters included, as small changes to the filter could be barely or entirely not visible, which in turn makes the filter less useful.

#### Third graph: Bar chart

**Purpose**

The third graph is used to compare LASSO and Ridge regression.

**Why this graph?**

A bar chart was chosen as this allows for clear comparison between two values. Considering the goal of graphic comparison of two quantiles using bar chart is the most suitable. The difference of height of two columns makes it clear and easy to detect the performance gap. Adopting two different colors for each test set results in even clearer distinction of the values. Eventually, the bar chart is friendly for using interactive tools. Adjusting the the train-test split proportion by an interactive slider produce immediate height change of the columns.

**Alternatives considered**

For the third graph no alternative was considered as the bar chart satisfied the desired purpose.

------------------------------------------------------------------------

# Data

## Data Source

The data set was sourced from Kaggle: https://www.kaggle.com/datasets/rounakbanik/pokemon The data was imported in may 2026.

## Data Structure

Brief overview of used variables:

| Variable       | Description                             |
|----------------|-----------------------------------------|
| name           | Name of the pokemon                     |
| attack         | Base attack stat                        |
| defense        | Base defense stat                       |
| speed          | Base speed stat                         |
| hp             | Amount of health points                 |
| sp_attack      | Special attack stat                     |
| sp_defense     | Special defense stat                    |
| generation     | Generation the pokemon is from          |
| type1          | First type of the pokemon               |
| type2          | Second type of the pokemon (optional)   |
| is_legendary   | Whether the pokemon is legendary or not |
| weight_kg      | Pokemon weight in kilograms             |
| height_m       | Pokemon height in metres                |
| pokedex_number | Index of pokemon entry in the pokedex   |

## Data Cleaning

The data did not need any cleaning or preprocessing to be used, for the functions included in this app preprocessed any catagorical data and all used models used columns without any missing values.

------------------------------------------------------------------------

# Packages Used

-   `shiny`
-   `dplyr`
-   `ggplot2`
-   `fmsb`
-   `glmnet`
